pipeline:
    name: june31
    identifier: june31
    projectIdentifier: Github_Repo_Level_Pipeline_Automation
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: q1
                                identifier: q1
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups: <+input>
                                    approverInputs: []
              tags: {}
