pipeline:
    name: Pipeline567
    identifier: Pipeline567
    projectIdentifier: projectu7uBJOTEHB
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: H1
              identifier: H1
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: A1
                                identifier: A1
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups: <+input>
                                    approverInputs: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: MarkAsSuccess
