connector:
  name: 'github automation '
  identifier: github_automation
  description:
  orgIdentifier: default
  projectIdentifier: oldExp
  type: Github
  spec:
    url: https://github.com/harness-automation/Gitx-automation
    authentication:
      type: Http
      spec:
        type: UsernameToken
        spec:
          username: harness-automation
          tokenRef: secret321
    apiAccess:
      type: Token
      spec:
        tokenRef: secret321
    executeOnDelegate: false
    type: Repo
